title: Joaquin Menendez
subtitle: Personal page
description: Personal page
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
avatar: Multimedia/images/avatar.jpeg


#contact
email: jm622@duke.edu
linkedin_url: https://www.linkedin.com/in/joaquin-menendez/
github_url: https://github.com/joaquinmenendez
googleplus_url: https://scholar.google.com/citations?user=QXAVig4AAAAJ&hl=en
